import { useState } from 'react';
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { AdminHousehold } from '../../lib/admin/server/repository';
import './AdminApp.css';

const api = '/api/admin';
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${api}${path}`, { ...init, headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? 'Something went wrong.'); return data as T; }
const format = (date: string | null) => date ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(date)) : '—';

function Dashboard() {
	const client = useQueryClient(); const [search, setSearch] = useState(''); const [notice, setNotice] = useState<string | null>(null); const [inviteUrl, setInviteUrl] = useState<string | null>(null);
	const households = useQuery({ queryKey: ['households', search], queryFn: () => request<{ households: AdminHousehold[] }>(`/households?q=${encodeURIComponent(search)}`).then((x) => x.households) });
	const refresh = () => client.invalidateQueries({ queryKey: ['households'] });
	const create = useMutation({ mutationFn: (body: unknown) => request('/households', { method: 'POST', body: JSON.stringify(body) }), onSuccess: () => { setNotice('Household created.'); refresh(); }, onError: (e) => setNotice(e.message) });
	const importBatch = useMutation({ mutationFn: async ({ file, expiresOn }: { file: File; expiresOn: string }) => { const response = await fetch(`${api}/import`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ csv: await file.text(), expiresOn }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error ?? 'Unable to import this batch.'); } const download = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = download; link.download = 'wedding-yamm-invitations.csv'; link.click(); URL.revokeObjectURL(download); }, onSuccess: () => { setNotice('Guests imported and YAMM invitation CSV downloaded. Keep that file private.'); refresh(); }, onError: (e) => setNotice(e.message) });
	const invite = useMutation({ mutationFn: (body: unknown) => request<{ url: string }>('/invitations', { method: 'POST', body: JSON.stringify(body) }), onSuccess: (data) => { setInviteUrl(data.url); refresh(); }, onError: (e) => setNotice(e.message) });
	const revoke = useMutation({ mutationFn: (id: string) => request(`/invitations?id=${id}`, { method: 'DELETE' }), onSuccess: () => { setNotice('Invitation revoked.'); refresh(); }, onError: (e) => setNotice(e.message) });
	const logout = async () => { await request('/logout', { method: 'POST' }); location.assign('/admin'); };
	return <section className="admin-shell panel"><header className="admin-header"><div><p className="admin-eyebrow">Private dashboard</p><h1>Wedding RSVP administration</h1><p>Create invitations, track responses, and export the guest list.</p></div><button className="admin-secondary" onClick={logout}>Sign out</button></header>
		{notice && <p className="admin-notice" role="status">{notice}</p>}
		{inviteUrl && <section className="admin-secret"><strong>Copy this invitation URL now.</strong><p>It will not be shown again after you close this message.</p><div><input readOnly value={inviteUrl} aria-label="New invitation URL" /><button onClick={() => navigator.clipboard.writeText(inviteUrl).then(() => setNotice('Invitation URL copied.'))}>Copy</button><button className="admin-secondary" onClick={() => setInviteUrl(null)}>Close</button></div></section>}
		<section className="admin-import"><h2>Import guest list and generate links</h2><p>Upload a CSV with: <code>Household key</code>, <code>Household name</code>, <code>Email</code>, and <code>Guest name</code>. Each row is one guest; all guests can attend both events.</p><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get('guestCsv'); const expiresOn = String(form.get('expiresOn') ?? ''); if (!(file instanceof File) || !file.size) { setNotice('Choose a guest-list CSV first.'); return; } importBatch.mutate({ file, expiresOn }); }}><label>Guest-list CSV<input name="guestCsv" type="file" accept=".csv,text/csv" required /></label><label>RSVP link expiry date <small>Links expire at 11:59 pm New Zealand time.</small><input name="expiresOn" type="date" min={new Date().toISOString().slice(0, 10)} required /></label><button disabled={importBatch.isPending}>{importBatch.isPending ? 'Importing…' : 'Import & download YAMM CSV'}</button></form></section>
		<section className="admin-create"><h2>Add one household</h2><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const names = String(form.get('guests')).split('\n').map((name) => name.trim()).filter(Boolean); create.mutate({ displayName: form.get('displayName'), primaryEmail: form.get('primaryEmail'), guests: names.map((fullName) => ({ fullName })) }); event.currentTarget.reset(); }}><input name="displayName" required maxLength={200} placeholder="Household name" /><input name="primaryEmail" required type="email" placeholder="Contact email" /><textarea name="guests" required maxLength={4000} placeholder="One guest name per line" /><button disabled={create.isPending}>{create.isPending ? 'Adding…' : 'Add household'}</button></form></section>
		<div className="admin-toolbar"><label>Search<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Household or email" /></label><a className="admin-secondary" href={`${api}/export.csv`}>Export CSV</a></div>
		{households.isLoading ? <p>Loading households…</p> : households.isError ? <p className="admin-error">{households.error.message}</p> : <div className="admin-list">{households.data?.map((household) => <Household key={household.id} household={household} onInvite={(expiresAt) => invite.mutate({ householdId: household.id, expiresAt })} onRevoke={(id) => revoke.mutate(id)} busy={invite.isPending || revoke.isPending} />)}{!households.data?.length && <p>No households found.</p>}</div>}
	</section>;
}
function Household({ household, onInvite, onRevoke, busy }: { household: AdminHousehold; onInvite: (expiresAt: string) => void; onRevoke: (id: string) => void; busy: boolean }) {
	const [open, setOpen] = useState(false); const active = household.invitations.find((invite) => !invite.revokedAt && new Date(invite.expiresAt) > new Date());
	return <article className="admin-household"><div className="admin-household-summary"><div><h2>{household.displayName}</h2><p>{household.primaryEmail} · {household.guests.length} guest{household.guests.length === 1 ? '' : 's'}</p></div><button className="admin-secondary" onClick={() => setOpen(!open)}>{open ? 'Hide' : 'View'}</button></div>{open && <div className="admin-household-detail"><p><strong>Invitation:</strong> {active ? `Active until ${format(active.expiresAt)}` : 'None active'}</p><form className="admin-invite-form" onSubmit={(event) => { event.preventDefault(); const expires = new FormData(event.currentTarget).get('expiresAt'); if (expires) onInvite(new Date(String(expires)).toISOString()); }}><input name="expiresAt" type="datetime-local" required defaultValue={new Date(Date.now() + 90 * 86400000).toISOString().slice(0, 16)} /><button disabled={busy}>Generate invitation</button>{active && <button type="button" className="admin-danger" disabled={busy} onClick={() => onRevoke(active.id)}>Revoke active link</button>}</form><ul>{household.guests.map((guest) => <li key={guest.id}><strong>{guest.fullName}</strong> · {guest.rsvpFor} · ceremony: {guest.ceremonyStatus ?? 'pending'} · reception: {guest.receptionStatus ?? 'pending'}{guest.dietaryRequirements.length ? ` · dietary: ${guest.dietaryRequirements.join(', ')}` : ''}</li>)}</ul>{household.additionalComments && <p><strong>Comments:</strong> {household.additionalComments}</p>}<p className="admin-meta">Created {format(household.createdAt)} · {household.invitations.length} invitation record{household.invitations.length === 1 ? '' : 's'}</p></div>}</article>;
}
const queryClient = new QueryClient();
export default function AdminApp() { return <QueryClientProvider client={queryClient}><Dashboard /></QueryClientProvider>; }
